# Generated by Django 4.2.6 on 2023-10-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_caracteristicas', models.CharField(blank=True, max_length=500)),
                ('otros', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ofimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SitemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('carnet', models.CharField(max_length=10)),
                ('extension', models.CharField(blank=True, max_length=5)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.cargo')),
                ('dispositivos', models.ManyToManyField(blank=True, to='forms.dispositivo')),
                ('encuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.encuesta')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='estandares_abiertos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estandares_abiertos', to='forms.nivel'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofimatica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.ofimatica'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='sistema_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.sitemaoperativo'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='software_libre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_libre', to='forms.nivel'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.tipodispositivo'),
        ),
    ]
